### ISSUE TITLE
error

### ISSUE THREAD

**Issue by livelylife** [Silverster98/pointops#2]
Collecting git+https://github.com/Silverster98/pointops (from -r requirements.txt (line 4))
  Cloning https://github.com/Silverster98/pointops to c:\users\23703\appdata\local\temp\pip-req-build-58qs_i9d
  Running command git clone --filter=blob:none --quiet https://github.com/Silverster98/pointops 'C:\Users\23703\AppData\Local\Temp\pip-req-build-58qs_i9d'
  Resolved https://github.com/Silverster98/pointops to commit 86c68b1e63092152b4ab14ff09b832c5d2d0dc97
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\23703\AppData\Local\Temp\pip-req-build-58qs_i9d\setup.py", line 9, in <module>
          flag for flag in opt.split() if flag != '-Wstrict-prototypes'
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Silverster98** [comment]
I recommend running the code on the Linux platform instead of Windows.

**Comment by QJSQJS** [comment]
Hello, the system I use is also Windows 10. After I deleted the 7-10 lines of code in the setup.py file, I ran pip install -e., and the installation was successful!

![a1](https://github.com/Silverster98/pointops/assets/48120697/8fa3ac12-1a72-465e-a153-b56acc348a7d)
