### ISSUE TITLE
_get_cuda_arch_flags     arch_list[-1] += '+PTX'

### ISSUE THREAD

**Issue by TobyZhouWei** [Silverster98/pointops#3]
Hi, I am struggle in building pointops recently. I meet the problems as followed
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    setup(
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/command/install.py", line 80, in run
    self.do_egg_install()
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/command/install.py", line 129, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
    build_ext.build_extensions(self)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 557, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 456, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/zw/anaconda3/envs/sam3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1626, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

I don not know why come out IndexError, could you give me some advice?

**Comment by Silverster98** [comment]
Please refer to [https://github.com/pytorch/extension-cpp/issues/71#issuecomment-1183674660](https://github.com/pytorch/extension-cpp/issues/71#issuecomment-1183674660).
